import {
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowLeftRight,
  Banknote,
  Building2,
  BarChart3,
  Check,
  ClipboardList,
  Clock,
  Box,
  Copy,
  FileText,
  Mail,
  AlertTriangle,
  IdCard,
  Info,
  KeyRound,
  Map,
  MapPin,
  Pencil,
  Play,
  Plus,
  ShieldCheck,
  LayoutGrid,
  Trash2,
  Truck,
  User,
  Users,
  UsersRound,
  Wallet,
  Wrench,
  X,
  Smartphone,
  Menu,
  ChevronsLeft,
  ChevronsRight,
  LogOut,
  SquareStack
} from '@lucide/vue'
import { createIconPack } from './_helpers'

export default createIconPack({
  id: 'lucide',
  label: 'Lucide',
  style: 'minimal',
  strokeWidth: 1.75,
  icons: {
    add: Plus,
    edit: Pencil,
    delete: Trash2,
    close: X,
    duplicate: Copy,
    check: Check,
    arrowLeft: ArrowLeft,
    arrowRight: ArrowRight,
    swap: ArrowLeftRight,
    document: FileText,
    wallet: Wallet,
    user: User,
    users: Users,
    userGroup: UsersRound,
    chart: BarChart3,
    archive: Archive,
    money: Banknote,
    building: Building2,
    clipboard: ClipboardList,
    clock: Clock,
    mapPin: MapPin,
    map: Map,
    identification: IdCard,
    wrench: Wrench,
    vehicle: Truck,
    grid: LayoutGrid,
    cube: Box,
    warning: AlertTriangle,
    play: Play,
    info: Info,
    envelope: Mail,
    shield: ShieldCheck,
    key: KeyRound,
    mobile: Smartphone,
    settings: Wrench,
    logout: LogOut,
    reports: BarChart3,
    dashboard: SquareStack,
    contractor: Users,
    equipment: Wrench,
    supplies: Archive,
    menu: Menu,
    chevronLeft: ChevronsLeft,
    chevronRight: ChevronsRight,
    pencil: Pencil,
    default: ClipboardList
  }
})
