import {
  PhPlus,
  PhPencilSimple,
  PhTrash,
  PhX,
  PhCopy,
  PhCheck,
  PhArrowLeft,
  PhArrowRight,
  PhArrowsLeftRight,
  PhFileText,
  PhWallet,
  PhUser,
  PhUsers,
  PhUsersThree,
  PhChartBar,
  PhArchive,
  PhMoney,
  PhBuildings,
  PhClipboardText,
  PhClock,
  PhMapPin,
  PhMapTrifold,
  PhIdentificationCard,
  PhWrench,
  PhTruck,
  PhSquaresFour,
  PhCube,
  PhWarning,
  PhPlay,
  PhInfo,
  PhEnvelope,
  PhShieldCheck,
  PhKey,
  PhDeviceMobile,
  PhGear,
  PhSignOut,
  PhList,
  PhCaretDoubleLeft,
  PhCaretDoubleRight
} from '@phosphor-icons/vue'
import { createIconPack } from './_helpers'

export default createIconPack({
  id: 'phosphor',
  label: 'Phosphor',
  style: 'rounded',
  strokeWidth: 0,
  icons: {
    add: PhPlus,
    edit: PhPencilSimple,
    delete: PhTrash,
    close: PhX,
    duplicate: PhCopy,
    check: PhCheck,
    arrowLeft: PhArrowLeft,
    arrowRight: PhArrowRight,
    swap: PhArrowsLeftRight,
    document: PhFileText,
    wallet: PhWallet,
    user: PhUser,
    users: PhUsers,
    userGroup: PhUsersThree,
    chart: PhChartBar,
    archive: PhArchive,
    money: PhMoney,
    building: PhBuildings,
    clipboard: PhClipboardText,
    clock: PhClock,
    mapPin: PhMapPin,
    map: PhMapTrifold,
    identification: PhIdentificationCard,
    wrench: PhWrench,
    vehicle: PhTruck,
    grid: PhSquaresFour,
    cube: PhCube,
    warning: PhWarning,
    play: PhPlay,
    info: PhInfo,
    envelope: PhEnvelope,
    shield: PhShieldCheck,
    key: PhKey,
    mobile: PhDeviceMobile,
    settings: PhGear,
    logout: PhSignOut,
    reports: PhChartBar,
    dashboard: PhSquaresFour,
    contractor: PhUsers,
    equipment: PhWrench,
    supplies: PhArchive,
    menu: PhList,
    chevronLeft: PhCaretDoubleLeft,
    chevronRight: PhCaretDoubleRight,
    pencil: PhPencilSimple,
    default: PhClipboardText
  }
})
