import {
  ArchiveBoxIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowsRightLeftIcon,
  BanknotesIcon,
  BuildingOffice2Icon,
  ChartBarIcon,
  CheckIcon,
  ClipboardDocumentListIcon,
  ClockIcon,
  CubeIcon,
  DocumentDuplicateIcon,
  DocumentTextIcon,
  EnvelopeIcon,
  ExclamationTriangleIcon,
  IdentificationIcon,
  InformationCircleIcon,
  KeyIcon,
  MapIcon,
  MapPinIcon,
  PencilIcon,
  PencilSquareIcon,
  PlayIcon,
  PlusIcon,
  ShieldCheckIcon,
  Squares2X2Icon,
  TrashIcon,
  TruckIcon,
  UserGroupIcon,
  UserIcon,
  UsersIcon,
  WalletIcon,
  WrenchScrewdriverIcon,
  XMarkIcon,
  DevicePhoneMobileIcon,
  Bars3Icon,
  ChevronDoubleLeftIcon,
  ChevronDoubleRightIcon,
  ArrowRightOnRectangleIcon
} from '@heroicons/vue/24/outline'
import { createIconPack } from '../helpers'

const pack = createIconPack({
  id: 'heroicons',
  label: 'Heroicons',
  style: 'outline',
  strokeWidth: 1.5,
  icons: {
    add: PlusIcon,
    edit: PencilSquareIcon,
    delete: TrashIcon,
    close: XMarkIcon,
    duplicate: DocumentDuplicateIcon,
    check: CheckIcon,
    arrowLeft: ArrowLeftIcon,
    arrowRight: ArrowRightIcon,
    swap: ArrowsRightLeftIcon,
    document: DocumentTextIcon,
    wallet: WalletIcon,
    user: UserIcon,
    users: UsersIcon,
    userGroup: UserGroupIcon,
    chart: ChartBarIcon,
    archive: ArchiveBoxIcon,
    money: BanknotesIcon,
    building: BuildingOffice2Icon,
    clipboard: ClipboardDocumentListIcon,
    clock: ClockIcon,
    mapPin: MapPinIcon,
    map: MapIcon,
    identification: IdentificationIcon,
    wrench: WrenchScrewdriverIcon,
    vehicle: TruckIcon,
    grid: Squares2X2Icon,
    cube: CubeIcon,
    warning: ExclamationTriangleIcon,
    play: PlayIcon,
    info: InformationCircleIcon,
    envelope: EnvelopeIcon,
    shield: ShieldCheckIcon,
    key: KeyIcon,
    mobile: DevicePhoneMobileIcon,
    settings: WrenchScrewdriverIcon,
    logout: ArrowRightOnRectangleIcon,
    reports: ChartBarIcon,
    dashboard: Squares2X2Icon,
    contractor: UsersIcon,
    equipment: WrenchScrewdriverIcon,
    supplies: ArchiveBoxIcon,
    menu: Bars3Icon,
    chevronLeft: ChevronDoubleLeftIcon,
    chevronRight: ChevronDoubleRightIcon,
    pencil: PencilIcon,
    default: ClipboardDocumentListIcon
  }
})

export default pack
export const { icons } = pack
